
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programaAND CAR CDR COND CONS DEFUN DIFERENTE DIVISAO DIVISAOINT IDENTIFICADOR IF IGUAL MAIOR MAIORIGUAL MAIS MENOR MENORIGUAL MENOS MULTIPLICACAO NIL NOT NUMERO OR PARENTESE_DIR PARENTESE_ESQ RESTOprograma : expressaoexpressao : atomo\n                 | definicao_funcao\n                 | expressao_if\n                 | expressao_aritmetica\n                 | expressao_comparacao\n                 | expressao_lista\n                 | lista_genericaatomo : NUMERO\n             | IDENTIFICADOR\n             | NILexpressao_aritmetica : PARENTESE_ESQ MAIS expressao expressao PARENTESE_DIR\n                            | PARENTESE_ESQ MENOS expressao expressao PARENTESE_DIR\n                            | PARENTESE_ESQ MULTIPLICACAO expressao expressao PARENTESE_DIR\n                            | PARENTESE_ESQ DIVISAOINT expressao expressao PARENTESE_DIRexpressao_comparacao : PARENTESE_ESQ IGUAL expressao expressao PARENTESE_DIR\n                            | PARENTESE_ESQ MAIOR expressao expressao PARENTESE_DIR\n                            | PARENTESE_ESQ MENOR expressao expressao PARENTESE_DIRexpressao_lista : PARENTESE_ESQ CAR expressao PARENTESE_DIR\n                       | PARENTESE_ESQ CDR expressao PARENTESE_DIRdefinicao_funcao : PARENTESE_ESQ DEFUN IDENTIFICADOR lista_parametros expressao PARENTESE_DIRlista_parametros : PARENTESE_ESQ lista_de_expressoes PARENTESE_DIRexpressao_if : PARENTESE_ESQ IF expressao expressao expressao PARENTESE_DIRlista_generica : PARENTESE_ESQ lista_de_expressoes PARENTESE_DIRlista_de_expressoes : expressao lista_de_expressoeslista_de_expressoes : expressaolista_de_expressoes : '
    
_lr_action_items = {'NUMERO':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,39,40,41,42,50,51,55,56,57,58,59,60,61,62,63,64,],[10,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,-24,10,10,10,-19,-20,-12,-13,-14,-15,-16,-17,-18,-22,-21,-23,]),'IDENTIFICADOR':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,39,40,41,42,50,51,55,56,57,58,59,60,61,62,63,64,],[11,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,11,27,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,-24,11,11,11,-19,-20,-12,-13,-14,-15,-16,-17,-18,-22,-21,-23,]),'NIL':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,39,40,41,42,50,51,55,56,57,58,59,60,61,62,63,64,],[12,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,-24,12,12,12,-19,-20,-12,-13,-14,-15,-16,-17,-18,-22,-21,-23,]),'PARENTESE_ESQ':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,27,29,30,31,32,33,34,35,36,39,40,41,42,50,51,55,56,57,58,59,60,61,62,63,64,],[13,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,13,13,13,13,13,13,13,13,13,13,13,13,40,13,13,13,13,13,13,13,13,-24,13,13,13,-19,-20,-12,-13,-14,-15,-16,-17,-18,-22,-21,-23,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,39,50,51,55,56,57,58,59,60,61,63,64,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-24,-19,-20,-12,-13,-14,-15,-16,-17,-18,-21,-23,]),'PARENTESE_DIR':([3,4,5,6,7,8,9,10,11,12,13,15,26,28,37,38,39,40,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,63,64,],[-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-27,-26,39,-25,50,51,-24,-27,55,56,57,58,59,60,61,-19,-20,62,63,64,-12,-13,-14,-15,-16,-17,-18,-21,-23,]),'DEFUN':([13,],[14,]),'IF':([13,],[16,]),'MAIS':([13,],[17,]),'MENOS':([13,],[18,]),'MULTIPLICACAO':([13,],[19,]),'DIVISAOINT':([13,],[20,]),'IGUAL':([13,],[21,]),'MAIOR':([13,],[22,]),'MENOR':([13,],[23,]),'CAR':([13,],[24,]),'CDR':([13,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'expressao':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[2,15,15,29,30,31,32,33,34,35,36,37,38,42,43,44,45,46,47,48,49,15,53,54,]),'atomo':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,]),'definicao_funcao':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'expressao_if':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,]),'expressao_aritmetica':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'expressao_comparacao':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'expressao_lista':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'lista_generica':([0,13,15,16,17,18,19,20,21,22,23,24,25,29,30,31,32,33,34,35,36,40,41,42,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'lista_de_expressoes':([13,15,40,],[26,28,52,]),'lista_parametros':([27,],[41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> expressao','programa',1,'p_programa','analizador.py',89),
  ('expressao -> atomo','expressao',1,'p_expressao','analizador.py',98),
  ('expressao -> definicao_funcao','expressao',1,'p_expressao','analizador.py',99),
  ('expressao -> expressao_if','expressao',1,'p_expressao','analizador.py',100),
  ('expressao -> expressao_aritmetica','expressao',1,'p_expressao','analizador.py',101),
  ('expressao -> expressao_comparacao','expressao',1,'p_expressao','analizador.py',102),
  ('expressao -> expressao_lista','expressao',1,'p_expressao','analizador.py',103),
  ('expressao -> lista_generica','expressao',1,'p_expressao','analizador.py',104),
  ('atomo -> NUMERO','atomo',1,'p_atomo','analizador.py',109),
  ('atomo -> IDENTIFICADOR','atomo',1,'p_atomo','analizador.py',110),
  ('atomo -> NIL','atomo',1,'p_atomo','analizador.py',111),
  ('expressao_aritmetica -> PARENTESE_ESQ MAIS expressao expressao PARENTESE_DIR','expressao_aritmetica',5,'p_expressao_aritmetica','analizador.py',118),
  ('expressao_aritmetica -> PARENTESE_ESQ MENOS expressao expressao PARENTESE_DIR','expressao_aritmetica',5,'p_expressao_aritmetica','analizador.py',119),
  ('expressao_aritmetica -> PARENTESE_ESQ MULTIPLICACAO expressao expressao PARENTESE_DIR','expressao_aritmetica',5,'p_expressao_aritmetica','analizador.py',120),
  ('expressao_aritmetica -> PARENTESE_ESQ DIVISAOINT expressao expressao PARENTESE_DIR','expressao_aritmetica',5,'p_expressao_aritmetica','analizador.py',121),
  ('expressao_comparacao -> PARENTESE_ESQ IGUAL expressao expressao PARENTESE_DIR','expressao_comparacao',5,'p_expressao_comparacao','analizador.py',127),
  ('expressao_comparacao -> PARENTESE_ESQ MAIOR expressao expressao PARENTESE_DIR','expressao_comparacao',5,'p_expressao_comparacao','analizador.py',128),
  ('expressao_comparacao -> PARENTESE_ESQ MENOR expressao expressao PARENTESE_DIR','expressao_comparacao',5,'p_expressao_comparacao','analizador.py',129),
  ('expressao_lista -> PARENTESE_ESQ CAR expressao PARENTESE_DIR','expressao_lista',4,'p_expressao_lista','analizador.py',135),
  ('expressao_lista -> PARENTESE_ESQ CDR expressao PARENTESE_DIR','expressao_lista',4,'p_expressao_lista','analizador.py',136),
  ('definicao_funcao -> PARENTESE_ESQ DEFUN IDENTIFICADOR lista_parametros expressao PARENTESE_DIR','definicao_funcao',6,'p_definicao_funcao','analizador.py',143),
  ('lista_parametros -> PARENTESE_ESQ lista_de_expressoes PARENTESE_DIR','lista_parametros',3,'p_lista_parametros','analizador.py',147),
  ('expressao_if -> PARENTESE_ESQ IF expressao expressao expressao PARENTESE_DIR','expressao_if',6,'p_expressao_if','analizador.py',151),
  ('lista_generica -> PARENTESE_ESQ lista_de_expressoes PARENTESE_DIR','lista_generica',3,'p_lista_generica','analizador.py',156),
  ('lista_de_expressoes -> expressao lista_de_expressoes','lista_de_expressoes',2,'p_lista_de_expressoes_multipla','analizador.py',162),
  ('lista_de_expressoes -> expressao','lista_de_expressoes',1,'p_lista_de_expressoes_unica','analizador.py',166),
  ('lista_de_expressoes -> <empty>','lista_de_expressoes',0,'p_lista_de_expressoes_vazia','analizador.py',170),
]
